### ISSUE TITLE
对于隐藏A的excel表格上传后，B列内容未正常显示。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#104]
对于隐藏A的excel表格上传后，B列内容未正常显示。将A列隐藏取消掉，A列内容正常显示，B列内容扔不显示。
[22.xlsx](https://github.com/iCloudWorkGroup/fengniao/files/840927/22.xlsx)
![1](https://cloud.githubusercontent.com/assets/22340050/23896070/f81d345a-08e2-11e7-9767-02332608c7af.png)

**Comment by wlchair** [comment]
@jhrgitgit ，看看这个问题是什么情况？
