### ISSUE TITLE
前进，后退功能

### ISSUE THREAD

**Issue by CJL5678** [iCloudWorkGroup/fengniao#120]

**Comment by wlchair** [comment]
这个月度目标，没看出来why，what，when，how这几个关键内容，
如果你现在不知道怎么定。
我这有一份图，项目现在需要做的事情，根据要做的功能，你选择目标，给出预计的完成时间
![tup](https://cloud.githubusercontent.com/assets/5516398/24139772/6aa244d2-0e58-11e7-80f9-22588b93eda4.png)
