### ISSUE TITLE
inc中，对于已隐藏的列取消隐藏后，原隐藏列中的内容未正常显示，双击单元格会显示原单元格中内容。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#138]
inc中，对于已隐藏的列取消隐藏后，原隐藏列中的内容未正常显示，双击单元格会显示原单元格中内容。
![1](https://cloud.githubusercontent.com/assets/22340050/24448043/7b1cbf4c-14a5-11e7-81af-26c33db7d6df.png)
![2](https://cloud.githubusercontent.com/assets/22340050/24448053/83717a02-14a5-11e7-9653-a4774295dd4e.png)
![3](https://cloud.githubusercontent.com/assets/22340050/24448066/889c87f6-14a5-11e7-84d4-bf531b2a7ab7.png)

**Comment by CJL5678** [comment]
问题已修复
