### ISSUE TITLE
写入效果和还原效果不一致

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#15]
**输入时的效果**
![normal](https://cloud.githubusercontent.com/assets/5516398/15998256/5d4d1440-316f-11e6-96f5-fd7e02867646.png)

**还原之后的效果**
![reduction](https://cloud.githubusercontent.com/assets/5516398/15998260/64bc3e4a-316f-11e6-973e-0da744f7a09f.png)

原因：宽度因为后端数据返回的错误，高度因为前端的计算错误

**Comment by CJL5678** [comment]
问题已经解决
