### ISSUE TITLE
有特殊格式后，不能粘入数据

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#2]
描述：如果从线下EXCEL中站入特殊格式的数据，站入不起作用，但是向后台发送了请求
测试的内容：![_xas 48ivjg2t 896oq90z](https://cloud.githubusercontent.com/assets/5516398/13835838/a63580c6-ec36-11e5-931c-3b3c302d3c7b.jpg)

**Comment by CJL5678** [comment]
问题已解决
