### ISSUE TITLE
第三方调用，setFontFamilySize方法找不到

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#224]
### 使用：

在实例对象上调用`setFontFamilySize`方法时，提示找不到方法

## 链接地址 ##

任意表：[http://excel-inc.acmr.com.cn/master/getscript/674ffb0b-534f-4703-8098-6b17ac1a819c](http://excel-inc.acmr.com.cn/master/getscript/674ffb0b-534f-4703-8098-6b17ac1a819c)

**Comment by CJL5678** [comment]
接口改名为setFontSize

**Comment by wlchair** [comment]
这个问题在最新的代码里改了吗？ @CJL5678 ，还没有对应该这个问题？
还是在文档里修改下就可以了？

**Comment by CJL5678** [comment]
代码已经修改了，只需要修改文档就可以
