### ISSUE TITLE
第三方调用，setSelectRegion调用迷惑

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#231]
### 调用
```javascript
var r = ss.setSelectRegion();
```
`r`  值为 `undefined`

### 疑惑
文档中提到 `切选鼠标选择操作类型` ，这句话指的是什么呢？描述中又描述 `切换至单元格选中操作` 这又是什么意思呢？应该怎么调用呢？
是从其他模式切换到普通选中的模式吗？

如果是这样的话，怎么没有获取选中区域的方法呢？

**Comment by CJL5678** [comment]
在操作区域内，鼠标操作包含多种类型
例如：普通的选中模式、数据元模式、高亮模式
setSelectRegion方法是切换为普通选中模式的状态
在后期修改接口文档后，会进行详细的说明
