### ISSUE TITLE
第三方调用，如何使用getPointByPosi方法

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#237]
## 问题描述 ##

根据`posi`，这个是什么？ 是这些吗：`5d` 、`[4d,5e]`、`d`
返回的`point`结构是什么？

### 迷惑

看了API之后，不理解它的作用是什么，应该在哪些场景下应用

**Comment by CJL5678** [comment]
result.point ={
      col: 'D',
      row:'5'
} 
外部实现拖拽，mouseup之后，通过坐标获取鼠标所在点，在对点进行相应设置
