### ISSUE TITLE
createAddCommentView和createEditComment 区别

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#238]
### 应用场景

- 单元格上没有备注，不管用哪些都会弹出 `commit` 框
- 单元格已经有备注，`add` 不能再进行了，`edit` 会弹框，主要区别在这里吗？

> 注：在测试时，备注还是有问题的，所有没法看到真实的区别

### 建议

从 `commit` 的使用上，也就是`add`, `edit`, `delete`三种方法可以直接调用，其中 `add` 和 `edit` 又是大部分重合，是不是应该延续前面API的风格，用 `set` 来代替它们呢？

`modifyComment`这个方法的意义在哪？

### 调用

```javascript
ss.createEditComment(sheetId,"example content", singlePoint);
```
这种形式就可以调用。
为什么文档里写的`comment.createEditComment`这种形式呢？

**Comment by CJL5678** [comment]
eidt：弹出框包含选中单元格的备注文本（但多选时不包含备注文本，由于多选时多个单元格的备注可能不同）
add：为空文本
可以把名字改为createEditCommentView ，代表显示弹出框，set是对备注信息直接设置
