### ISSUE TITLE
第三方调用，regionchange不能被触发

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#242]
### 预期
根据文档描述，应该在任何移动选区操作时，触发该事件。

### 疑问
当`regionChange`和`selectRegionChange`同时存在时，应该先触发谁？
如果希望在多种事件情况下，触发同一个函数，为什么不使用类`jquery`风格处理？

**Comment by CJL5678** [comment]
说明文档含有错误，事件名字为regionChange，待后期修改
先触发regionChange后触发selectRegionChange
