### ISSUE TITLE
自动换行，换行后文字显示不全

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#28]
先增大字体再换行，换行后文字显示不全。
![pic](https://wt-prj.oss.aliyuncs.com/7d36230da61d4ca5aa5a497986c6ba09/579f8571-b157-4e15-9964-5d74407d4674.png)

**Comment by CJL5678** [comment]
e4c3647fafd6c0cb54914d45597a7724347e71a9
