### ISSUE TITLE
解决前端含有依赖DOM模块测试问题  熟悉TDD的编码方式

### ISSUE THREAD

**Issue by CJL5678** [iCloudWorkGroup/fengniao#282]
1.周一至周四： 
           一、研究出对于视图层进行单元测试方法：
                （1）解决对于缓存变量的依赖
                （2）解决对于测试方法对于其他方法的依赖
                （3）解决对于方法中对于dom的依赖
           二、项目添加reload接口
2. 周五：做出相应Demo

**Comment by wlchair** [comment]
分解目标，把工作任务量化。
学习和工作过程结合，在工作中学习推进。 @CJL5678
