### ISSUE TITLE
数据还原高度计算

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#3]
**正常流程步骤**
1. 前端读取高端，
2. 向后台请求数据显示区域的高度（等同读取的高度）
3. 返回对应的数据
**现状**
1. 前端没有发请求给后台。
2. 后台默认值为800px。

**Comment by CJL5678** [comment]
fixed #3

**Comment by CJL5678** [comment]
Fixed #3

**Comment by CJL5678** [comment]
Fixed #3 已经完成修改
