### ISSUE TITLE
数据源选择，出现多个重复框

### ISSUE THREAD

**Issue by wlchair** [iCloudWorkGroup/fengniao#6]
数据源选择功能，冻结的状态下会出出现个多选择框。而且是错误的。
解决方案建议：参考选择域方式，尽量重用。不要单独写逻辑，让代码冗余

**Comment by wlchair** [comment]
问题还是存在
![lh f c 56 u9 _16up ke](https://cloud.githubusercontent.com/assets/5516398/14105339/928fa136-f5dd-11e5-90fd-3c371db6e955.png)，
@CJL5678

**Comment by CJL5678** [comment]
现在已经修复此bug
