### ISSUE TITLE
数据上传后，前台小数位部分显示为NaN

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#86]
原数据设置为一位小数，在模板中心上传后，一位小数小数点后两位为两个0的数据，在前台显示为NaN，双击显示正确。

**Comment by witchgirl** [comment]
![1](https://cloud.githubusercontent.com/assets/22340050/19547245/0208f7f6-96c9-11e6-97a5-976eb0019284.png)

**Comment by CJL5678** [comment]
该问题已解决
