### ISSUE TITLE
数字格式中增加一位、三位小数；

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#89]
![2](https://cloud.githubusercontent.com/assets/22340050/23248796/438a98da-f9dc-11e6-8142-2a8b6b934c5b.png)
数字格式中增加一位、三位小数；目前只有0、2、4位

**Comment by wlchair** [comment]
请二位@CJL5678 @jhrgitgit 解决以后在这回复下 @witchgirl

**Comment by CJL5678** [comment]
已经协调添加完成，需等到录入库发布新版时
