### ISSUE TITLE
模板中心中，剪贴板中复制粘贴按钮不能使用。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#92]
模板中心中，剪贴板中复制粘贴按钮不能使用。使用“复制”按钮复制单元格或单元格内容，选择“粘贴”后，不显示内容。
url：http://192.168.1.178:8080/acmrinput30/templatecenter/TemplateHandel.htm?m=updateTemplateView&modId=8250599e-381e-4f64-a61c-3629ec7fe980&sort=M&templatesort=

**Comment by CJL5678** [comment]
已经开放了剪切板的接口，使用时，需要第三方进行调用
