### ISSUE TITLE
模板中心中，通过系统设定好的批注在excel界面能正常显示，点击保存后，设置未保存上。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#93]
模板中心中，通过系统设定好的批注在excel界面能正常显示，点击保存后，设置未保存上。
图1为过程文件，图2为保存后。

![1](https://cloud.githubusercontent.com/assets/22340050/23496342/98364a92-ff58-11e6-806d-1a888a996395.png)
![2](https://cloud.githubusercontent.com/assets/22340050/23496341/97f6d59c-ff58-11e6-86d4-22a6afd538ec.png)

**Comment by wlchair** [comment]
这个保存功能是通过`INPUT`系统处理的，廖锦可以帮你处理 @witchgirl
