### ISSUE TITLE
冻结问题反馈：冻结拆分窗口，进行滚条竖滚操作，返回后页面显示内容与原始表显示不一致。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#95]

**Comment by witchgirl** [comment]
冻结问题反馈：冻结拆分窗口，进行滚条竖滚操作，返回后页面显示内容与原始表显示不一致。
冻结首列也出现同样问题。
取消冻结后，原表显示恢复正常。
![1](https://cloud.githubusercontent.com/assets/22340050/23535377/f1019712-fff8-11e6-8edd-5fe69eba695e.png)
![2](https://cloud.githubusercontent.com/assets/22340050/23535384/fc5f3c7c-fff8-11e6-88df-ac5dfb6acf27.png)
![3](https://cloud.githubusercontent.com/assets/22340050/23535388/0131a2b2-fff9-11e6-9478-cff521c60013.png)

**Comment by CJL5678** [comment]
项目最新版本中已解决此问题
