### ISSUE TITLE
数据显示问题：原始表格与导入表格显示的数据不一致。

### ISSUE THREAD

**Issue by witchgirl** [iCloudWorkGroup/fengniao#96]
数据显示问题：原始表格与导入表格显示的数据不一致。原始为常规或者自定义格式时，浮点数读取值与原值与出入，希望能够显示excel表格值，双击时显示读取的真实值。
![1](https://cloud.githubusercontent.com/assets/22340050/23536711/ca7c4f3e-0001-11e7-9c0a-f64400e95fb0.png)
![2](https://cloud.githubusercontent.com/assets/22340050/23536713/cec489a8-0001-11e7-85c9-a85148d8be3b.png)
[excel显示表格值.xlsx](https://github.com/iCloudWorkGroup/fengniao/files/815713/excel.xlsx)

**Comment by wlchair** [comment]
Issue moved to [iCloudWorkGroup/table #35](https://github.com/iCloudWorkGroup/table/issues/35) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wlchair** [comment]
在table项目中已经解决
